# Generated by Django 3.1 on 2020-08-26 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id класса')),
                ('name', models.CharField(max_length=255, verbose_name='имя класса')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id файла')),
                ('name', models.CharField(max_length=255, verbose_name='имя файла')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id группы')),
                ('code', models.IntegerField(verbose_name='номер группы')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id записи')),
                ('code', models.IntegerField(verbose_name='номер записи')),
                ('incoming_liability', models.FloatField(verbose_name='входящий пассив')),
                ('incoming_asset', models.FloatField(verbose_name='входящий актив')),
                ('debit', models.FloatField(verbose_name='обороты-дебет')),
                ('credit', models.FloatField(verbose_name='обороты-кредит')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountancy.class')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountancy.file')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountancy.group')),
            ],
        ),
    ]
